version: '3.8'

services:
  db:
    image: postgres:17
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "8001:5432"
    healthcheck:
      test: pg_isready
      interval: 5s
      timeout: 5s
      retries: 5
    env_file:
      - .env

  django:
    build: .
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    depends_on:
      - db
    ports:
      - "8000:8000"
    env_file:
      - .env

volumes:
  postgres_data: